version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        volumes:
            - ./laravel_app:/var/www/html
        ports:
            - "8080:80" # Access Laravel at http://localhost:8080
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: db_name
            DB_USERNAME: db_username
            DB_PASSWORD: db_password
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - laravel

    mysql:
        image: mysql:8
        container_name: laravel_mysql
        restart: always
        environment:
            # MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_name
            MYSQL_USER: db_username
            MYSQL_PASSWORD: db_password
        ports:
            - "3307:3306" # MySQL accessible on host at port 3307
        volumes:
            - ./mysql_data:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-udb_username",
                    "-pdb_password",
                ]
            interval: 10s
            retries: 5
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64 # Force AMD64 if ARM build has issues on M1/M2
        container_name: laravel_phpmyadmin
        restart: always
        ports:
            - "8081:80" # Access phpMyAdmin at http://localhost:8081
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            # MYSQL_ROOT_PASSWORD: db_password
        depends_on:
            - mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
